name: Realty
version: "${version}"
main: io.github.md5sha256.realty.Realty
api-version: "1.21.8"
authors: [ md5sha256 ]
dependencies:
  server:
    Vault:
      join-classpath: true
      required: true
    WorldGuard:
      join-classpath: true
      required: true
    Essentials:
      join-classpath: true
      required: false
permissions:
  realty.command.agent.add:
    description: Allows using /realty agent add
    default: op
  realty.command.agent.remove:
    description: Allows using /realty agent remove
    default: op
  realty.command.add:
    description: Allows using /realty add
    default: op
  realty.command.add.others:
    description: Allows adding players/groups to regions you don't own
    default: op
  realty.command.remove:
    description: Allows using /realty remove
    default: op
  realty.command.remove.others:
    description: Allows removing players/groups from regions you don't own
    default: op
  realty.command.help:
    description: Allows using /realty help
    default: true
  realty.command.info:
    description: Allows using /realty info
    default: true
  realty.command.list:
    description: Allows using /realty list
    default: true
  realty.command.delete:
    description: Allows using /realty delete
    default: op
  realty.command.delete.includeworldguard:
    description: Allows deleting WorldGuard regions alongside realty regions
    default: op
  realty.command.create.sale:
    description: Allows using /realty create sale
    default: op
  realty.command.create.lease:
    description: Allows using /realty create lease
    default: op
  realty.command.offer.send:
    description: Allows using /realty offer send
    default: true
  realty.command.offer.inbox:
    description: Allows using /realty offer inbox
    default: true
  realty.command.offer.outbox:
    description: Allows using /realty offer outbox
    default: true
  realty.command.offer.accept:
    description: Allows using /realty offer accept
    default: op
  realty.command.offer.pay:
    description: Allows using /realty offer pay
    default: true
  realty.command.offer.withdraw:
    description: Allows using /realty offer withdraw
    default: true
  realty.command.auction:
    description: Allows using /realty auction (create)
    default: op
  realty.command.auction.cancel:
    description: Allows using /realty auction cancel
    default: op
  realty.command.auction.bid:
    description: Allows using /realty auction bid
    default: true
  realty.command.buy:
    description: Allows using /realty buy
    default: true
  realty.command.auction.paybid:
    description: Allows using /realty auction paybid
    default: true
  realty.command.renewlease:
    description: Allows using /realty renewlease
    default: true
  realty.command.rent:
    description: Allows using /realty rent
    default: true
  realty.command.set.price:
    description: Allows using /realty set price
    default: op
  realty.command.set.duration:
    description: Allows using /realty set duration
    default: op
  realty.command.set.landlord:
    description: Allows using /realty set landlord
    default: op
  realty.command.set.titleholder:
    description: Allows using /realty set titleholder
    default: op
  realty.command.set.tenant:
    description: Allows using /realty set tenant
    default: op
  realty.command.unset.price:
    description: Allows using /realty unset price
    default: op
  realty.command.unset.titleholder:
    description: Allows using /realty unset titleholder
    default: op
  realty.command.unset.tenant:
    description: Allows using /realty unset tenant
    default: op
  realty.command.reload:
    description: Allows using /realty reload
    default: op
