name: Realty
version: "${version}"
main: io.github.md5sha256.realty.Realty
api-version: "1.21.8"
authors: [ md5sha256 ]
dependencies:
  server:
    Vault:
      join-classpath: true
      required: true
    WorldGuard:
      join-classpath: true
      required: true
    Essentials:
      join-classpath: true
      required: false
permissions:
  realty.command.add:
    description: Allows using /realty add
    default: op
  realty.command.add.others:
    description: Allows adding players/groups to regions you don't own
    default: op
  realty.command.remove:
    description: Allows using /realty remove
    default: op
  realty.command.remove.others:
    description: Allows removing players/groups from regions you don't own
    default: op
  realty.command.help:
    description: Allows using /realty help
    default: true
  realty.command.info:
    description: Allows using /realty info
    default: true
  realty.command.list:
    description: Allows using /realty list
    default: true
  realty.command.delete:
    description: Allows using /realty delete
    default: op
  realty.command.delete.includeworldguard:
    description: Allows deleting WorldGuard regions alongside realty regions
    default: op
  realty.command.create.sale:
    description: Allows using /realty create sale
    default: op
  realty.command.create.lease:
    description: Allows using /realty create lease
    default: op
  realty.command.offer:
    description: Allows using /realty offer
    default: true
  realty.command.payoffer:
    description: Allows using /realty payoffer
    default: true
  realty.command.acceptoffer:
    description: Allows using /realty acceptoffer
    default: op
  realty.command.withdrawoffer:
    description: Allows using /realty withdrawoffer
    default: true
  realty.command.offers:
    description: Allows using /realty offers (outbound/inbound)
    default: true
  realty.command.auction:
    description: Allows using /realty auction
    default: op
  realty.command.bid:
    description: Allows using /realty bid
    default: true
  realty.command.paybid:
    description: Allows using /realty paybid
    default: true
  realty.command.renewlease:
    description: Allows using /realty renewlease
    default: true
  realty.command.rent:
    description: Allows using /realty rent
    default: true
  realty.command.setprice:
    description: Allows using /realty setprice
    default: op
  realty.command.unsetprice:
    description: Allows using /realty unsetprice
    default: op
  realty.command.reload:
    description: Allows using /realty reload
    default: op
  realty.command.cancelauction:
    description: Allows using /realty cancelauction
    default: op