ALTER TABLE LeaseholdHistory
    MODIFY COLUMN eventType ENUM (
        'RENT', 'UNRENT', 'RENEW', 'LEASEHOLD_EXPIRY',
        'SET_DURATION', 'SET_LANDLORD', 'SET_TENANT', 'UNSET_TENANT', 'SET_MAX_EXTENSIONS',
        'SET_PRICE'
    ) NOT NULL;
